// The M·ass·euse wordmark: Charis SIL outlines with the purple stress wave
// under "ass", generated by tools/brand/build_brand.py from the same geometry
// as the printed advert. Inlined so the letters take `currentColor` and the
// shape needs no extra request.

import wordmark from './wordmark.svg?raw';

interface Props {
    className?: string;
}

export function Wordmark({ className = '' }: Props) {
    return (
        <span
            role="img"
            aria-label="masseuse.ai"
            className={`wordmark block ${className}`}
            dangerouslySetInnerHTML={{ __html: wordmark }}
        />
    );
}
