// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ShellInfo is what the window knows about itself.
 */
export interface ShellInfo {
    /**
     * Version is the shell's own version; the connector's is in its hello.
     */
    "version": string;
    "os": string;

    /**
     * StateDir is where the connector keeps its identity, pairings and
     * choices; the Help menu opens it.
     */
    "stateDir": string;

    /**
     * Wired says whether the connector is running behind the window.
     */
    "wired": boolean;

    /**
     * LogFile is where the connector's log goes (Help, "Show the log").
     */
    "logFile": string;
}

/**
 * SourceChoice is the camera and microphone the person picked, or a camera
 * on the network; the fields are the connector's own flags (its
 * cmd/masseuse-camlink/source.go, sourceConfig), and a set_source changes
 * only the part they speak of.
 */
export interface SourceChoice {
    "camera"?: string;
    "mic"?: string;
    "videoSize"?: string;
    "fps"?: number;
    "bitrate"?: string;
    "encoder"?: string;
    "url"?: string;
    "fingerprint"?: string;

    /**
     * FaceCamera is the camera that carries OBS's picture back to the room
     * as the person's face (the connector's -face-camera); "phone" offers
     * none, and the phone's own camera is the face view, straight to the
     * room.
     */
    "faceCamera"?: string;

    /**
     * Share is whether the connector offers the phone's picture to this
     * computer for OBS (-share-phone on or off); nil leaves it as it is.
     */
    "share"?: boolean | null;
}
