// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectorService is the window's side of the link to masseuse-camlink.
 * Its exported methods are what the page can ask for; Wails generates the
 * TypeScript for them (frontend/bindings). What the connector reports comes
 * the other way, as "connector" events the page listens to; the shell's
 * own words go the same way (the connector stopped, "blocked"; the
 * system's standing on the camera and the microphone, "media").
 * 
 * The service starts the connector as a child on ServiceStartup
 * (cmd/masseuse-camlink -ipc, docs/DESKTOP.md section 3), relays the JSON
 * lines it writes as events, sends the page's requests down its standard
 * input, and ends it on ServiceShutdown. The last event of each kind is
 * kept, so a page that mounts after the connector has spoken gets the
 * state (Snapshot). The connector ending with the relaunch code after an
 * update is the cue to start the whole program again (relaunch.go); any
 * other end is reported to the page, which can start it again.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Info describes the shell.
 */
export function Info(): $CancellablePromise<$models.ShellInfo> {
    return $Call.ByID(6507478);
}

/**
 * ListDevices asks the connector for the cameras and microphones it can
 * open; the answer arrives as a "devices" event.
 */
export function ListDevices(): $CancellablePromise<void> {
    return $Call.ByID(1697856389);
}

/**
 * OpenLink opens one of the known pages in the default browser.
 */
export function OpenLink(name: string): $CancellablePromise<void> {
    return $Call.ByID(3947855358, name);
}

/**
 * OpenPrivacySettings opens the system's settings where the camera and the
 * microphone are allowed to this application: on a Mac, System Settings ›
 * Privacy & Security, on the Camera pane while the camera is not allowed
 * and on the Microphone pane otherwise. Nothing elsewhere.
 */
export function OpenPrivacySettings(): $CancellablePromise<void> {
    return $Call.ByID(3539469259);
}

/**
 * Quit ends the program: the camera goes off and the unit is released on
 * the way out, as with the window's close button.
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(3866359469);
}

/**
 * RequestMediaAccess asks the system for the camera and the microphone:
 * on a Mac the two prompts in turn, while the standing is not determined
 * (a refusal is answered at once, without a prompt; System Settings is the
 * way back, OpenPrivacySettings). It returns at once, and the answer is a
 * "media" event once both are answered. One ask runs at a time: asked
 * again while the prompts are up, nothing more happens, the answer to the
 * first covers it. The page asks when the Cameras screen opens (or Ready,
 * on a computer paired before) and on its Allow button; elsewhere than a
 * Mac there is nothing to ask and the standing is authorized.
 */
export function RequestMediaAccess(): $CancellablePromise<void> {
    return $Call.ByID(328903251);
}

/**
 * Restart starts the connector again after it stopped.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(2997123545);
}

/**
 * RevealStateDir shows the state directory in the file manager.
 */
export function RevealStateDir(): $CancellablePromise<void> {
    return $Call.ByID(2803868243);
}

/**
 * SelectUnit serves the stimulation unit with this id from the list the
 * connector reported; the unit let go is put to zero first. It is refused
 * while a session has the unit armed.
 */
export function SelectUnit(id: string): $CancellablePromise<void> {
    return $Call.ByID(315454280, id);
}

/**
 * SetSource chooses the camera and microphone (or the network camera), the
 * front-facing camera, or whether the phone's picture is wanted. The
 * connector applies it while no session reads the camera and remembers
 * it for the next start; the result comes back as a "source" event.
 */
export function SetSource(choice: $models.SourceChoice): $CancellablePromise<void> {
    return $Call.ByID(2953673043, choice);
}

/**
 * ShowLog reveals the connector's log in the file manager.
 */
export function ShowLog(): $CancellablePromise<void> {
    return $Call.ByID(2597378075);
}

/**
 * Snapshot is the last event of each kind the connector has sent, in the
 * order to replay them: a page that mounts after the connector spoke reads
 * its state from these before the live events.
 */
export function Snapshot(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(1979382394);
}

/**
 * UpdateNow has the connector look for a newer release at once instead of
 * at its next check.
 */
export function UpdateNow(): $CancellablePromise<void> {
    return $Call.ByID(2889761785);
}
